name: Send slack message
description: 'Send slack messages, requires a json array'
inputs:
  messages:
    description: 'messages to be sent'
runs:
  using: 'composite'
  steps:
    - name: Generate message json
      shell: bash
      run: |
        messages=$(echo '${{ inputs.messages }}' | jq -r '.[]')
        message='{"blocks": []}'
        echo $messages | while read item; do
          obj='[{"type":"section","text":{"type":"mrkdwn","text":"'$item'"}}]'
          message=$(echo $message | jq --argjson arr_obj "$obj" '.blocks += $arr_obj')
        done
