name: 'My Action'
description: 'A simple GitHub Action with an output'
inputs:
  name:
    description: 'The name to greet'
    required: true
    default: 'World'
outputs:
  greeting:
    description: 'The greeting message'
runs:
  using: 'composite'
  steps:
    - run: |
        echo "::set-output name=greeting::Hello, $INPUT_NAME!"
      shell: bash
    env:
      INPUT_NAME: ${{ inputs.name }}