name: 'My Action'
description: 'A simple GitHub Action with an output'
inputs:
  name:
    description: 'The name to greet'
    required: true
    default: 'World'
outputs:
  greeting:
    description: 'The greeting message'
    value: ${{ steps.test.outputs.greeting }}
runs:
  using: 'composite'
  steps:
    - shell: bash
      id: test
      run: |
        echo "::set-output name=greeting::Hello, ${{ inputs.name }}!"