name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout  # Step ID

      - name: Run build
        run: echo "Building..."
        id: build_step  # Step ID

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check build status
        run: |
          status=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs \
              | jq -r --arg job_name "$job" '.jobs[] | select(.name==build)')
          echo $status
