name: Inspect launchd on GitHub macOS Runner

on:
  push:
  workflow_dispatch:

jobs:
  inspect-launchd:
    runs-on: macos-latest

    steps:
      - name: Print basic runner info
        run: |
          echo "Runner name: $RUNNER_NAME"
          echo "Runner OS: $RUNNER_OS"
          echo "Runner user: $(whoami)"
          echo "System version:"
          sw_vers
          ps -ef|grep runner
          sudo cat /Users/runner/Library/LaunchAgents/hca.plist
          sudo cat /opt/hca/start_hca.sh
          sudo cat /opt/hca/hosted-compute-agent

      - name: List all launchd services
        run: |
          echo "=== launchctl list ==="
          launchctl list

      - name: Look for GitHub-related launch agents
        run: |
          echo "=== Looking for GitHub-related launchd services ==="
          launchctl list | grep -i github || echo "No github-related services found"

      - name: Find runner plist files
        run: |
          echo "=== Searching for runner-related plist files ==="
          sudo find /Library/LaunchDaemons /Library/LaunchAgents /Users -name "*.plist" 2>/dev/null | grep -i runner || echo "No runner plist found"

      - name: Print GitHub Actions environment variables
        run: |
          echo "=== GitHub Actions Env Variables ==="
          env | grep -i github
