name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        id: checkout  # Step ID

      - name: Run build
        run: echo "Building..."
        id: build_step  # Step ID

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check build status
        run: |
          echo $GITHUB_REPOSITORY
          echo $GITHUB_RUN_ID
          status=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs)
          echo $status
