name: Generate Matrix from Output

on:
  push:
    branches:
      - main

jobs:
  job-a:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.get-token.outputs.auth_token }}
    steps:
      - id: get-token
        run: |
          echo "::set-output name=auth_token::{[\"a\",\"b\"]}"

  job-b:
    runs-on: ubuntu-latest
    needs: job-a
    strategy:
      matrix:
        value: ${{fromJson(needs.job-a.outputs.json)}}
    steps:
      - run: |
          echo Current: "${{ matrix.value }}"
