name: Generate Matrix from Output
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      charts: ${{ steps.export_vars.outputs.charts }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Export variables
        id: export_vars
        run: |
          charts+=$(cat .github/workflows/config.json | jq   '.explorer_charts' |jq -c "."| sed 's/"/\\"/g' )
          echo "charts: $charts"
          echo "charts=$charts" >> $GITHUB_OUTPUT

  job2:
    needs: [ job1 ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart: ${{fromJson(needs.job1.outputs.charts)}}
    steps:
      - run: |
          echo Current: "${{ matrix.chart }}"
