name: Generate Matrix from Output
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - id: matrix
        run: |
          echo "matrix=[\"1\",\"2\"]" >> $GITHUB_OUTPUT

  job2:
    needs: [ job1 ]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.job1.outputs.matrix)}}
    steps:
      - run: |
          echo Current: "${{ matrix.value }}"
