name: Generate Matrix from Output

on:
  push:
    branches:
      - main

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    outputs:
      json: ${{ steps.generate-matrix.outputs.json }}
    steps:
      - name: Generate Matrix
        id: generate-matrix
        run: |
          # Your script to generate the matrix
          echo "::set-output name=json::{[\"a\",\"b\"]}"

  use-matrix:
    needs: generate-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ needs.generate-matrix.outputs.json }}
    steps:
      - name: Print Matrix Values
        run: |
          echo "Matrix Value: ${{ matrix.value }}"
