# This is a basic workflow to help you get started with Actions

name: vault

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
        type: string
      commit:
        description: 'Commit ID'
        type: string

jobs:
  retrieve-secret:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Retrieve secret from Vault
        uses: hashicorp/vault-action@v3.0.0
        with:
          method: jwt
          url: k8s-vault-vaultui-9ef6f0c587-cebb6b5285c15bd8.elb.us-east-1.amazonaws.com:8200
          role: rippled-antithesis
          secrets: rippled-antithesis/data/test test

      - name: Use secret from Vault
        run: |
          # This step has access to the secret retrieved above; see hashicorp/vault-action for more details.
