name: test
on: [push, pull_request]
jobs:

  test:
    strategy:
      matrix:
        include:
          - site: "production"
            datacenter: "site-a"
          - site: "staging"
            datacenter: "site-b"
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: XRPLF/clio
          path: clio
          ref: 3f58b3e40176591a29521e82842967a82e8d2aef
          fetch-depth: 0
      - name: install Ninja on Linux
        if: startsWith(matrix.site,'production')
        run: |
          #sleep 600
          echo "${{ matrix.site }}"
