name: Test Environment Reviewers

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Environment name to inspect"
        required: true
        default: "official-release"
      package_name:
        description: "Package name"
        required: true
        default: "xrpl"
      package_version:
        description: "Package version"
        required: true
        default: "0.0.0-test"

permissions:
  contents: read
  actions: read

jobs:
  show_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Compute executor
        id: who
        run: |
          # executor = the person who triggered the pipeline
          EXECUTOR="${{ github.triggering_actor || github.actor }}"
          echo "executor=$EXECUTOR" >> "$GITHUB_OUTPUT"

      - name: Fetch environment and extract reviewers
        id: reviewers
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          ENV_NAME: ${{ github.event.inputs.env_name }}
        run: |
          set -euo pipefail

          ENV_JSON="$(curl -sSf \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/environments/$ENV_NAME")"
          
          echo "Raw environment JSON fetched."
          echo "$ENV_JSON" | jq -r '.name as $n | "Environment: \($n)"'
          
          REVIEWERS="$(printf '%s' "$ENV_JSON" | jq -r '
            (.protection_rules // [])
            | map(select(.type=="required_reviewers") | .reviewers // [])
            | add // []
            | map(
                if .type=="User" then (.reviewer.login)
                elif .type=="Team" then (.reviewer.slug)
                else (.reviewer.login // .reviewer.slug // "unknown")
                end
              )
            | unique
            | join(", ")
          ')"
          
          if [ -z "$REVIEWERS" ] || [ "$REVIEWERS" = "null" ]; then
            REVIEWERS="(no required reviewers configured)"
          fi
          
          echo "reviewers=$REVIEWERS" 
